spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/auth-service
server:
    port: 8080


auth-service:
    app:
        jwtSecret: SecretKey
        jwtExpirationMs: 86400000