spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Password
        url: jdbc:mysql://127.0.0.1:3306/GIG_ECONOMY
        username: root
server:
    port: 8080